apiVersion: v1
kind: ConfigMap
metadata:
  name: glb-config
  namespace: demo
data:
  haproxy.cfg: |
    global
        log stdout format raw local0

    defaults
        log global
        mode http
        option httplog
        option dontlognull

        timeout connect 10s
        timeout client 60s
        timeout server 60s

    frontend http
        bind *:80
        default_backend apache_backend

    backend apache_backend
        balance roundrobin

        option httpchk HEAD /
        http-check expect status 200

        default-server inter 5s fall 3 rise 2

        server apache1 192.168.1.191:80 check
        server apache2 192.168.1.192:80 check
        server apache3 192.168.1.193:80 check

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glb
  namespace: demo
  labels:
    app: glb
spec:
  replicas: 1

  selector:
    matchLabels:
      app: glb

  template:
    metadata:
      labels:
        app: glb

    spec:
      containers:
      - name: haproxy
        image: haproxy:2.9
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 80

        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy

      volumes:
      - name: config
        configMap:
          name: glb-config

---
apiVersion: v1
kind: Service
metadata:
  name: glb
  namespace: demo

spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.195

  selector:
    app: glb

  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
